project_id = "pvwwxpcosiqetsflykmp"

[functions.sommelier-chat]
verify_jwt = false

[functions.create-viva-payment]
verify_jwt = false

[functions.viva-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.send-order-confirmation]
verify_jwt = false

[functions.generate-colissimo-label]
verify_jwt = false

[functions.social-content]
verify_jwt = false

[functions.colissimo-find-relay-points]
verify_jwt = false
