// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "Lister le catalogue",
  description: "Liste les fleurs, r\xE9sines et accessoires actifs du catalogue High Society Botanicals avec prix au gramme, taux de CBD et gamme.",
  inputSchema: {
    category: z.string().trim().optional().describe("Filtre optionnel sur la cat\xE9gorie (ex. fleur, resine, accessoire)."),
    limit: z.number().int().min(1).max(50).optional().describe("Nombre maximum de produits (d\xE9faut 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("products").select(
      "id, name, subtitle, category, price, price_group, cbd_percentage, is_force_noire, is_nectar_divin, mood, terpenes"
    ).eq("is_active", true).order("display_order", { ascending: true }).limit(limit ?? 20);
    if (category) query = query.ilike("category", `%${category}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool2({
  name: "list_my_orders",
  title: "Mes commandes",
  description: "Liste les commandes du client connect\xE9 (num\xE9ro, statut, montant, mode de livraison, date).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Nombre maximum de commandes (d\xE9faut 10)."),
    status: z2.string().trim().optional().describe("Filtre optionnel sur le statut de commande.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orders").select(
      "id, display_order_number, order_number, status, payment_status, total_amount, total_flower_weight, delivery_type, delivery_date, tracking_number, tracking_url, created_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order-details.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_order_details_default = defineTool3({
  name: "get_order_details",
  title: "D\xE9tail d'une commande",
  description: "Retourne le d\xE9tail d'une commande du client connect\xE9 (produits, poids, prix) \xE0 partir de son num\xE9ro de commande (ex. HSB-123456).",
  inputSchema: {
    order_number: z3.string().trim().min(3).describe("Num\xE9ro de commande, ex. HSB-123456.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: order, error } = await supabase.from("orders").select(
      "id, display_order_number, order_number, status, payment_status, total_amount, total_flower_weight, delivery_type, delivery_address, delivery_date, tracking_number, tracking_url, created_at"
    ).eq("user_id", ctx.getUserId()).or(`display_order_number.eq.${order_number},order_number.eq.${order_number}`).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!order) {
      return { content: [{ type: "text", text: `Commande ${order_number} introuvable.` }], isError: true };
    }
    const { data: items, error: itemsError } = await supabase.from("order_items").select("product_name, product_type, weight, quantity, unit_price, total_price").eq("order_id", order.id);
    if (itemsError) return { content: [{ type: "text", text: itemsError.message }], isError: true };
    const result = { order, items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-my-account.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_account_default = defineTool4({
  name: "get_my_account",
  title: "Mon compte",
  description: "Retourne le profil du client connect\xE9 : coordonn\xE9es, statut pro, et avancement du programme de fid\xE9lit\xE9 (grammes offerts disponibles).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "email, full_name, city, postal_code, company_name, is_pro_validated, qualifying_orders_count, free_grams_available"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Profil introuvable." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pvwwxpcosiqetsflykmp";
var mcp_default = defineMcp({
  name: "high-society-botanicals",
  title: "High society botanicals",
  version: "0.1.0",
  instructions: "Outils de la boutique High Society Botanicals. `list_products` expose le catalogue public (fleurs, r\xE9sines, accessoires). `get_my_account`, `list_my_orders` et `get_order_details` agissent au nom du client connect\xE9 et ne renvoient que ses propres donn\xE9es.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_my_account_default, list_my_orders_default, get_order_details_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
